
services:
  caddy:
    image: caddy:2-alpine
    container_name: proxy_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"   # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data       # certificats Let's Encrypt (PERSISTANT)
      - caddy-config:/config
    networks:
      - web

networks:
  web:
    external: true

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local
