name: Commit Lint

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: 📝 Validate commit messages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Valide tous les commits de la PR (de la base jusqu'au HEAD de la PR).
      - name: 📝 Run commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js
