name: Main CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker/**"
      - ".github/workflows/**"
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  security-events: write
  contents: read
  actions: read
  id-token: write

jobs:
  build-and-test:
    uses: ./.github/workflows/build-unit-tests.yml

  code-quality-sast:
    needs: build-and-test
    uses: ./.github/workflows/code-quality-sast.yml
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  secret-scanning:
    needs: build-and-test
    uses: ./.github/workflows/secret-scanning.yml

  sca-dependency-scan:
    needs: build-and-test
    uses: ./.github/workflows/sca-dependency-scan.yml

  unused-deps:
    needs: build-and-test
    uses: ./.github/workflows/unused-deps.yml

  secure-iac-dockerfile-scan:
    needs: build-and-test
    uses: ./.github/workflows/secure-iac-dockerfile-scan.yml

  phpstan:
    needs: build-and-test
    uses: ./.github/workflows/phpstan.yml

  mutation-tests:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/mutation-tests.yml

  build-and-scan-docker:
    needs: [code-quality-sast, secret-scanning, secure-iac-dockerfile-scan, sca-dependency-scan, unused-deps, phpstan]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      app_name: ${{ vars.DEPLOY_APPLI_NAME }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-docker-hub:
    needs: [build-and-scan-docker]
    uses: ./.github/workflows/publish-docker-hub.yml
    with:
      app_name: ${{ vars.DEPLOY_APPLI_NAME }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dast-zap-test:
    needs: publish-docker-hub
    uses: ./.github/workflows/dast-zap-test.yml
    with:
      app_name: ${{ vars.DEPLOY_APPLI_NAME }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      LARAVEL_APP_KEY: ${{ secrets.LARAVEL_APP_KEY }}

  build-and-test-front:
    uses: ./.github/workflows/build-unit-tests-front.yml

  code-quality-sast-front:
    needs: build-and-test-front
    uses: ./.github/workflows/code-quality-sast-front.yml
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  sca-dependency-scan-front:
    needs: build-and-test-front
    uses: ./.github/workflows/sca-dependency-scan-front.yml

  unused-deps-front:
    needs: build-and-test-front
    uses: ./.github/workflows/unused-deps-front.yml

  secure-iac-dockerfile-scan-front:
    needs: build-and-test-front
    uses: ./.github/workflows/secure-iac-dockerfile-scan-front.yml

  codeql-front:
    needs: build-and-test-front
    uses: ./.github/workflows/codeql-front.yml

  e2e-playwright-front:
    needs: build-and-test-front
    uses: ./.github/workflows/e2e-playwright-front.yml

  lighthouse-ci-front:
    needs: build-and-test-front
    uses: ./.github/workflows/lighthouse-ci-front.yml

  build-and-scan-docker-front:
    needs: [code-quality-sast-front, secret-scanning, secure-iac-dockerfile-scan-front, sca-dependency-scan-front, unused-deps-front, codeql-front, e2e-playwright-front, lighthouse-ci-front]
    uses: ./.github/workflows/build-docker-image-front.yml
    with:
      app_name: ${{ vars.DEPLOY_APPLI_NAME_FRONT }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-docker-hub-front:
    needs: [build-and-scan-docker-front]
    uses: ./.github/workflows/publish-docker-hub-front.yml
    with:
      app_name: ${{ vars.DEPLOY_APPLI_NAME_FRONT }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dast-zap-test-front:
    needs: publish-docker-hub-front
    uses: ./.github/workflows/dast-zap-test-front.yml
    with:
      app_name: ${{ vars.DEPLOY_APPLI_NAME_FRONT }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: [dast-zap-test, mutation-tests, dast-zap-test-front]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      backend_image: ${{ vars.DEPLOY_APPLI_NAME }}
      frontend_image: ${{ vars.DEPLOY_APPLI_NAME_FRONT }}
    secrets: inherit

  send-notifications:
    needs:
      - build-and-test
      - code-quality-sast
      - secret-scanning
      - sca-dependency-scan
      - unused-deps
      - secure-iac-dockerfile-scan
      - phpstan
      - mutation-tests
      - build-and-scan-docker
      - publish-docker-hub
      - dast-zap-test
      - build-and-test-front
      - code-quality-sast-front
      - sca-dependency-scan-front
      - unused-deps-front
      - secure-iac-dockerfile-scan-front
      - codeql-front
      - e2e-playwright-front
      - lighthouse-ci-front
      - build-and-scan-docker-front
      - publish-docker-hub-front
      - dast-zap-test-front
      - deploy
    uses: ./.github/workflows/send-notifications.yml
    if: always()
    secrets:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_TO: ${{ secrets.MAIL_TO }}
    with:
      result_build_and_test: ${{ needs.build-and-test.result }}
      result_code_quality_sast: ${{ needs.code-quality-sast.result }}
      result_secret_scanning: ${{ needs.secret-scanning.result }}
      result_sca_dependency_scan: ${{ needs.sca-dependency-scan.result }}
      result_unused_deps: ${{ needs.unused-deps.result }}
      result_secure_iac_dockerfile_scan: ${{ needs.secure-iac-dockerfile-scan.result }}
      result_phpstan: ${{ needs.phpstan.result }}
      result_mutation_tests: ${{ needs.mutation-tests.result }}
      result_build_and_scan_docker: ${{ needs.build-and-scan-docker.result }}
      result_publish_docker_hub: ${{ needs.publish-docker-hub.result }}
      result_dast_zap_test: ${{ needs.dast-zap-test.result }}
      result_build_and_test_front: ${{ needs.build-and-test-front.result }}
      result_code_quality_sast_front: ${{ needs.code-quality-sast-front.result }}
      result_sca_dependency_scan_front: ${{ needs.sca-dependency-scan-front.result }}
      result_unused_deps_front: ${{ needs.unused-deps-front.result }}
      result_secure_iac_dockerfile_scan_front: ${{ needs.secure-iac-dockerfile-scan-front.result }}
      result_codeql_front: ${{ needs.codeql-front.result }}
      result_e2e_playwright_front: ${{ needs.e2e-playwright-front.result }}
      result_lighthouse_ci_front: ${{ needs.lighthouse-ci-front.result }}
      result_build_and_scan_docker_front: ${{ needs.build-and-scan-docker-front.result }}
      result_publish_docker_hub_front: ${{ needs.publish-docker-hub-front.result }}
      result_dast_zap_test_front: ${{ needs.dast-zap-test-front.result }}
      result_deploy: ${{ needs.deploy.result }}
